### ISSUE TITLE
Madcast does not seem to be able to generate polymorphic code

### ISSUE THREAD

**Issue by Kerl13** [Niols/ppx_deriving_madcast#1]
For instance

```ocaml
let id = [%madcast: 'a -> 'a] in
…
```

Generates

```ocaml
let id = (fun x -> x : 'a -> 'a) in
…
```

Which Is monomorphic because of the type annotation

**Comment by Niols** [comment]
Thanks to Victor Lancin, I now see two possible fixes for that issue:

1. either we say that `'a -> 'a` is a monomorphic type annotation and that, if polymorphism is needed, the type annotation must explicit it: `'a. 'a -> 'a`. This requires a slight modification in the way we match the given type and an other in the way we annotate the output code.

2. or we say that we always generalize the type annotations automatically. This requires the two previous modifications and a function that generalizes a type. However, I don't think this is the right way to go, as it would be annoying for people wanting specific type annotations not to be generalized.

I, personnaly, would go for the first fix. I think it's pretty easy to implement an makes a lot of sense. Any opinion?

**Comment by Niols** [comment]
Hm. Let me come back on what I said. In fact, in the parser, there can only be a "core_type" in a [% ... : ...] PPX, meaning we can't ask people to generalize their type there.

So either we go for 2. or we abandon type annotations in the derived code. For now, I don't see any other solution.

**Comment by Niols** [comment]
I will go for the full generalization all the time. It is still better than no annotation. And I don't think we will ever fall in the case where it becomes annoying
